version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management # RabbitMQ with management plugin
    container_name: rabbitmq-container
    ports:
      - "5672:5672"  # RabbitMQ AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  app:
    build:
      context: . # The directory containing your Dockerfile
    container_name: app-container
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq # Reference RabbitMQ by its service name
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - app_network
    ports:
      - "3000:3000" # Expose your Express app's port

networks:
  app_network:
    driver: bridge
