version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management # RabbitMQ with management plugin
    container_name: rabbitmq-container
    ports:
      - "5672:5672"  # RabbitMQ AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8090:8090"       # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount configuration files
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
